name: Test hu-tao-supremacy/homebrew-buf
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          brew tap bufbuild/buf 2>/dev/null
          brew install buf --quiet 2>/dev/null
