name: Test hu-tao-supremacy/homebrew-buf
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          brew unlink go@1.15
          brew install go@1.16
          brew link --overwrite go@1.16
          brew tap hu-tao-supremacy/buf
          brew install buf --ignore-dependencies
