name: Test hu-tao-supremacy/homebrew-buf
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          BIN="/usr/local/bin"
          VERSION="0.39.1"
          BINARY_NAME="buf"
          curl -sSL "https://github.com/bufbuild/buf/releases/download/v${VERSION}/${BINARY_NAME}-$(uname -s)-$(uname -m)" -o "${BIN}/${BINARY_NAME}"
          chmod +x "${BIN}/${BINARY_NAME}"
          which buf
