name: Test hu-tao-supremacy/homebrew-buf
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          which go
          brew tap bufbuild/buf
          brew install buf --ignore-dependencies
