name: Test hu-tao-supremacy/homebrew-buf
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.0"
      - run: |
          brew tap hu-tao-supremacy/buf
          brew install buf
