name: Generate (Experimental)
on:
  push:
    branches:
      - experimental
    paths:
      - "!gen/**"
      - "proto/**"
      - ".github/**"
      - ".bazelignore"
      - "WORKSPACE"
      - "Makefile"
      - "BUILD"
jobs:
  generate:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        platform: [go, python, java, ts]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.DODOCO_BOT_PAT }}
      - run: echo "SHA7=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ hashFiles('WORKSPACE') }}-${{ hashFiles('BUILD') }}
      - run: brew install tree
      - run: make setup
      - run: |
          make build-${{ matrix.platform }}
          tree gen/
