name: Generate (Standalone)
on:
  push:
    branches:
      - main
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          brew install tree
          make setup
          make generate-linux
      - run: |
          tree gen/
