name: Generate
on:
  push:
    paths:
      - '!gen/**'
jobs:
  generate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          echo "SHA7=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - run: |
          export HOMEBREW_NO_AUTO_UPDATE=1

          brew install tree

          brew install protobuf

          brew install protoc-gen-go-grpc
          brew install protoc-gen-go

          sudo python3 -m pip install grpcio
          sudo python3 -m pip install grpcio-tools

          sudo yarn

          sudo wget https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.35.0/protoc-gen-grpc-java-1.35.0-osx-x86_64.exe
          sudo mv protoc-gen-grpc-java-1.35.0-osx-x86_64.exe protoc-gen-grpc-java
          sudo chmod +x protoc-gen-grpc-java
          sudo mv protoc-gen-grpc-java /usr/local/bin/.
          which protoc-gen-grpc-java

          brew tap bufbuild/buf
          brew install buf
      - run: |
          git checkout -b gen/${{ env.SHA7 }}
          rm -rf gen/
          make generate
          git add -f gen/
          git commit -m 'build: ${{ env.SHA7 }}'
        env:
          GIT_COMMITTER_NAME: dodoco-bot
          GIT_AUTHOR_NAME: dodoco-bot
          EMAIL: 77519537+dodoco-bot@users.noreply.github.com
      - run: |
          tree gen/
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DODOCO_BOT_PAT }}
          branch: gen/${{ env.SHA7 }}
  pull-request:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "SHA7=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - uses: repo-sync/pull-request@v2
        with:
          source_branch: gen/${{ env.SHA7 }}
          destination_branch: "main"
          github_token: ${{ secrets.DODOCO_BOT_PAT }}
