name: Generate (Standalone)
on:
  push:
    branches:
      - main
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ hashFiles('BUILD') }}
      - run: brew install tree
      - run: make setup
      - run: make generate-linux
      - run: |
          tree gen/
