name: Generate (Standalone)
on:
  push:
    branches:
      - main
jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [go, python, java, ts]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        if: ${{ matrix.platform != "ts" }}
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ hashFiles('BUILD') }}
      - run: brew install tree
      - run: make setup
      - run: make build-${{ matrix.platform }}
      - run: |
          tree gen/
