name: Generate
on:
  push:
    branches:
      - main
jobs:
  generate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          echo $PATH
      - run: |
          export HOMEBREW_NO_AUTO_UPDATE=1

          brew install tree

          brew install protobuf

          brew install protoc-gen-go-grpc
          brew install protoc-gen-go

          sudo python3 -m pip install grpcio
          sudo python3 -m pip install grpcio-tools

          sudo yarn

          sudo wget https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.35.0/protoc-gen-grpc-java-1.35.0-osx-x86_64.exe
          sudo mv protoc-gen-grpc-java-1.35.0-osx-x86_64.exe protoc-gen-grpc-java
          sudo chmod +x protoc-gen-grpc-java
          sudo mv protoc-gen-grpc-java /usr/local/bin/.
          which protoc-gen-grpc-java

          brew tap bufbuild/buf
          brew install buf
      - run: |
          echo "${GITHUB_SHA:7}"
          make generate
      - run: |
          tree gen/
