name: Generate (Standalone)
on:
  push:
    branches:
      - main
    paths:
      - "!gen/**"
      - "proto/**"
      - ".github/**"
      - "BUILD"
      - "WORKSPACE"
jobs:
  generate:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        platform: [go, python, java, ts]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.DODOCO_BOT_PAT }}
      - run: echo "SHA7=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ hashFiles('WORKSPACE') }}-${{ hashFiles('BUILD') }}
      - run: make setup
      - run: |
          git checkout -b compile/${{ env.SHA7 }}/${{ matrix.platform }}
          make build-${{ matrix.platform }}
          git commit --allow-empty -m 'compile(${{ matrix.platform }}): ${{ env.SHA7 }}'
        env:
          GIT_COMMITTER_NAME: dodoco-bot
          GIT_AUTHOR_NAME: dodoco-bot
          EMAIL: 77519537+dodoco-bot@users.noreply.github.com
      - run: git push "https://x-access-token:${{ secrets.DODOCO_BOT_PAT }}@github.com/$GITHUB_REPOSITORY.git" "compile/${{ env.SHA7 }}/${{ matrix.platform }}"
  merge-all:
    needs: generate
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: "main"
          token: ${{ secrets.DODOCO_BOT_PAT }}
      - run: echo "SHA7=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - run: |
          !(git diff --quiet --name-only main origin/compile/${{ env.SHA7 }}/go) && \
            git merge -q origin/compile/${{ env.SHA7 }}/go

          !(git diff --quiet --name-only main origin/compile/${{ env.SHA7 }}/python) && \
            git merge -q origin/compile/${{ env.SHA7 }}/python

          !(git diff --quiet --name-only main origin/compile/${{ env.SHA7 }}/java) && \
            git merge -q origin/compile/${{ env.SHA7 }}/java

          !(git diff --quiet --name-only main origin/compile/${{ env.SHA7 }}/ts) && \
            git merge -q origin/compile/${{ env.SHA7 }}/ts
        env:
          GIT_COMMITTER_NAME: dodoco-bot
          GIT_AUTHOR_NAME: dodoco-bot
          EMAIL: 77519537+dodoco-bot@users.noreply.github.com
      - run: git push "https://x-access-token:${{ secrets.DODOCO_BOT_PAT }}@github.com/$GITHUB_REPOSITORY.git" "main"
  delete-all:
    needs: merge-all
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        platform: [go, python, java, ts]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: "main"
          token: ${{ secrets.DODOCO_BOT_PAT }}
      - run: echo "SHA7=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - run: |
          git push origin --delete compile/${{ env.SHA7 }}/${{ matrix.platform }}
        env:
          GIT_COMMITTER_NAME: dodoco-bot
          GIT_AUTHOR_NAME: dodoco-bot
          EMAIL: 77519537+dodoco-bot@users.noreply.github.com
