name: Generate on PR
on:
  pull_request:
    paths:
      - "proto/**"
jobs:
  generate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          make setup
          make generate
      - run: |
          tree gen/
