name: Generate on PR
on:
  pull_request:
    paths:
      - "proto/**"
jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [go, python, java, ts]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-${{ hashFiles('WORKSPACE') }}-${{ hashFiles('BUILD') }}
      - run: make setup
      - run: make build-${{ matrix.platform }}
